apiVersion: v1
kind: Service
metadata:
  name: vistaar-backend
  namespace: vistaar
spec:
  selector:
    app: vistaar-backend
  ports:
    - port: 80
      targetPort: 8000
      name: http
  type: ClusterIP
